const menuCard = [
  {
    img: "/images/MenuItemsNB/cappucino.png",
    title: "Cappucino",
    description: "A bold espresso with steamed milk and a rich, velvety foam top.",
    smallprice: "R43",
    mediumprice: "R49",
    largeprice: "R55",
  },
  {
    img: "/images/MenuItemsNB/latte.png",
    title: "Latte",
    description: "Smooth espresso blended with creamy steamed milk for a mellow pick-me-up.",
    smallprice: "R43",
    mediumprice: "R49",
    largeprice: "R55",
  },
  {
    img: "/images/MenuItemsNB/americano.png",
    title: "Americano",
    description: "A rich espresso diluted with hot water for a bold, smooth sip.",
    smallprice: "R37",
    mediumprice: "R41",
    largeprice: "R46",
  },
  {
    img: "/images/MenuItemsNB/espresso.png",
    title: "Espresso",
    description: " Pure, intense coffee flavor in a small but mighty shot.",
    smallprice: "R32 (single)",
    mediumprice: "R35 (double)",
    largeprice: "N/A",
  },
  {
    img: "/images/MenuItemsNB/mocha.png",
    title: "Mocha",
    description: "A luscious fusion of espresso, steamed milk, and indulgent chocolate",
    smallprice: "R48",
    mediumprice: "R58",
    largeprice: "R65",
  },
  {
    img: "/images/MenuItemsNB/flatwhite.png",
    title: "Flat White",
    description: "Strong espresso with a silky milk texture for perfect balance.",
    smallprice: "R44",
    mediumprice: "N/A",
    largeprice: "N/A",
  },
  {
    img: "/images/MenuItemsNB/cortado.png",
    title: "Cortado",
    description: "Espresso softened with an equal part of warm milk – smooth and bold.",
    smallprice: "R40",
    mediumprice: "N/A",
    largeprice: "N/A",
  },
  {
    img: "/images/MenuItemsNB/macchiato.png",
    title: "Macchiato",
    description: "A shot of espresso topped with a dollop of foam – strong and simple.",
    smallprice: "R43",
    mediumprice: "N/A",
    largeprice: "N/A",
  },
  {
    img: "/images/MenuItemsNB/hotchocolate.png",
    title: "Hot Chocolate",
    description: "Rich, creamy, and comforting – a chocolate lover’s dream.",
    smallprice: "R46",
    mediumprice: "R53",
    largeprice: "R60",
  },
  {
    img: "/images/MenuItemsNB/chailatte.png",
    title: "Chai Latte",
    description: "Spiced black tea with frothy milk – sweet, spicy, and warming.",
    smallprice: "R46",
    mediumprice: "R52",
    largeprice: "R58",
  },
]
const menuCard2 = [
  {
    img: "/images/MenuItemsNB/icedcoffee.png",
    title: "Iced Coffee",
    description: "Freshly brewed coffee poured over ice – simple and energizing.",
    smallprice: "R35",
    mediumprice: "R40",
    largeprice: "R45",
  },
  {
    img: "/images/MenuItemsNB/icedlatte.png",
    title: "Iced Latte",
    description: "Chilled espresso and cold milk for a cool, creamy boost.",
    smallprice: "R40",
    mediumprice: "R45",
    largeprice: "R50",
  },
  {
    img: "/images/MenuItemsNB/coldbrew.png",
    title: "Cold Brew",
    description: "Smooth, slow-steeped coffee with deep, bold flavor.",
    smallprice: "R45",
    mediumprice: "R50",
    largeprice: "R55",
  },
  {
    img: "/images/MenuItemsNB/icedmocha.png",
    title: "Iced Mocha",
    description: "Cold coffee meets chocolate and milk for a sweet chill.",
    smallprice: "R50",
    mediumprice: "R55",
    largeprice: "R60",
  },
  {
    img: "/images/MenuItemsNB/machalatte.png",
    title: "Iced Matcha Latte",
    description: "Earthy matcha and milk over ice – fresh, vibrant, and green.",
    smallprice: "R50",
    mediumprice: "R55",
    largeprice: "R60",
  },
  {
    img: "/images/MenuItemsNB/icedtea.png",
    title: "Iced Tea",
    description: "Cool, refreshing tea served chilled for a perfect pick-me-up.",
    smallprice: "R20",
    mediumprice: "R25",
    largeprice: "R30",
  },
];
const menuCard3 = [
  {
    img: "/images/MenuItemsNB/herbaltea.png",
    title: "Herbal Tea",
    description: "Naturally caffeine-free, calming blends of pure herbal goodness.",
    smallprice: "R40",
  },
  {
    img: "/images/MenuItemsNB/rooibostea.png",
    title: "Rooibos Tea",
    description: "Earthy, naturally sweet, and soothing with no caffeine.",
    smallprice: "R65",
  },
  {
    img: "/images/MenuItemsNB/chai.png",
    title: "Chai",
    description: "A bold mix of black tea and exotic spices, brewed to warm the soul.",
    smallprice: "R75",
  },
  {
    img: "/images/MenuItemsNB/chamomiletea.png",
    title: "Chamomile Tea",
    description: "Light, floral, and perfect for relaxing moments.",
    smallprice: "R55",
  },
  {
    img: "/images/MenuItemsNB/whitetea.png",
    title: "White Tea",
    description: "Delicate and subtly sweet, a light and refreshing choice.",
    smallprice: "R80",
  },
  {
    img: "/images/MenuItemsNB/hibiscus.png",
    title: "Hibiscus Tea",
    description: "Vibrant, tart, and fruity – a refreshing caffeine-free brew.",
    smallprice: "R60",
  },
]
const menuCard4 = [
  {
    img: "/images/MenuItemsNB/chocmuffin.png",
    title: "Chocolate Chip",
    description: "Soft muffin loaded with melty chocolate chips.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/vanillamuffin.png",
    title: "Vanilla",
    description: "Classic and comforting with a sweet vanilla essence.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/capmuffin.png",
    title: "Cappuccino",
    description: "Coffee-infused muffin with a touch of mocha magic.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/blueberrymuffin.png",
    title: "Blueberry",
    description: "Bursting with juicy blueberries in a tender crumb.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/branmuffin.png",
    title: "Bran",
    description: "Hearty and wholesome, perfect for a nutritious snack.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/lemonmuffin.png",
    title: "Lemon",
    description: "Bright and zesty with a citrusy kick.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/applemuffin.png",
    title: "Apple Cinnamon",
    description: "Warm apple flavor spiced with a hint of cinnamon.",
    smallprice: "R30",
  },
]
const menuCard5 = [
  {
    img: "/images/MenuItemsNB/chocchipcookie.png",
    title: "Chocolate",
    description: "Classic never goes out of style — crisp edges, gooey chocolate centers, and pure cookie bliss.",
    smallprice: "R20",
  },
  {
    img: "/images/MenuItemsNB/oatmealcookies.png",
    title: "Oatmeal",
    description: "Wholesome oats, a touch of spice, and just the right chew — the comforting cookie you didn’t know you needed.",
    smallprice: "R20",
  },
  {
    img: "/images/MenuItemsNB/peanutbutterbiscuit.png",
    title: "Peanut Butter",
    description: "Sweet, salty, and nutty — with a soft center that melts in your mouth.",
    smallprice: "R20",
  },
  {
    img: "/images/MenuItemsNB/snickerdoodle.png",
    title: "Snickerdoodle",
    description: "Cinnamon-sugar coated and perfectly soft — a cozy twist on your usual cookie fix.",
    smallprice: "R20",
  },
  {
    img: "/images/MenuItemsNB/butterbiscuits.png",
    title: "Butter Biscuits",
    description: "Melt-in-your-mouth goodness with rich, buttery flavor — simple, satisfying, and utterly delicious.",
    smallprice: "R20",
  },
  {
    img: "/images/MenuItemsNB/coconutbiscuit.png",
    title: "Coconut",
    description: "Tropical and toasty — golden-baked biscuits with a delicious coconut twist.",
    smallprice: "R20",
  },
]
const menuCard6 = [
  {
    img: "/images/MenuItemsNB/carrotcake.png",
    title: "Carrot Cake",
    description: "Moist, spiced, and topped with rich cream cheese frosting.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/cheesecake.png",
    title: "Cheesecake",
    description: "Creamy, smooth, and set on a buttery biscuit base.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/choccake.png",
    title: "Chocolate Cake",
    description: "Rich, dark, and indulgent — a chocoholic’s dream.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/redvelvet.png",
    title: "Red Velvet Cake",
    description: "Hints of cocoa with cream cheese layers — smooth and striking.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/poundcake.png",
    title: "Pound Cake",
    description: "Dense, buttery, and perfect with coffee or tea.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/lemondrizzle.png",
    title: "Lemon Drizzle",
    description: "Light sponge with a sweet, zesty lemon glaze",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/almondcake.png",
    title: "Almond Cake",
    description: "Soft, nutty, and subtly sweet.",
    smallprice: "R30",
  },
  {
    img: "/images/MenuItemsNB/spongecake.png",
    title: "Victoria Sponge",
    description: "Fluffy layers with jam and whipped cream — a true classic.",
    smallprice: "R30",
  },
]
export {menuCard, menuCard2, menuCard3, menuCard4, menuCard5,menuCard6};
